#!/bin/sh

files=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$")
if [ "$files" = "" ]; then 
    exit 0 
fi
dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

pass=true

echo "Validating JavaScript..."

for file in ${files}; do
    jshint --config ${dir}/.jshintrc ${file}
    if [ $? != 0 ]; then
        pass=false
    fi
done

echo "JavaScript validation complete"

if ! $pass; then
    echo "Your commit contains files that should pass JSHint but do not. Please fix the JSHint errors and try again."
    exit 1
else
    echo "COMMIT SUCCEEDED"
fi
